#!/bin/sh
# 開発環境セットアップ用シェルスクリプト
# (課題)このファイルと、
# wsl-homeのショートカット作成vbs
# を一度で実行できるようにしたい

#
# 引数で指定したserviceが起動していなければ、起動させる関数
#
service_start () {
  service $1 status >/dev/null 2>&1
  if [ $? = 0 ]; then
    echo $1 is already running!!
  else
    sudo service $1 start
  fi
}

#
# main
#

service_start docker
service_start smbd

echo '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'
echo 'WSL ipadress:'
ip addr show |
  grep 'eth0' -A5 |
  grep 'inet ' |
  awk '{print $2}' |
  sed -e 's/\/20//'


